FROM amazonlinux:2023

RUN dnf install -y \
        gcc gcc-c++ make cmake git pkgconf-pkg-config \
        clang llvm-devel \
        rdma-core libibverbs libibverbs-devel libibverbs-utils \
        liburing-devel \
        libbpf-devel elfutils-libelf-devel \
        openssl-devel \
        python3 python3-pip python3-devel \
        iproute procps-ng which tar xz \
    && dnf clean all

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
      | sh -s -- -y --no-modify-path --default-toolchain 1.94 \
          --component rustfmt --component clippy

WORKDIR /work
CMD ["bash"]
